[technote]
id = "SITCOMTN-148"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-148.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-148"
github_default_branch = "main"
date_created = 2024-11-07T13:28:15Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Aaron"
name.family = "Roodman"
internal_id = "roodmana"
orcid = "https://orcid.org/0000-0001-5326-3486"
[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "2575 Sand Hill Rd., Menlo Park, CA 94025, USA"
